In [2]:
import pdfplumber
import pandas as pd

In [3]:
import os
import time
folder = r"C:\Users\yadav\Downloads\JSL Internship codes\JSL Internship Project\Daily Documents"

while True:

    # Get all PDF files
    pdf_files = [os.path.join(folder, file) for file in os.listdir(folder) if file.lower().endswith(".pdf")]
    
    if pdf_files:
        # Get the latest PDF
        latest_pdf = max(pdf_files, key=os.path.getmtime)
        print("Latest PDF:", latest_pdf)
    else:
        print("No PDF found.")

    time.sleep(10)      # Check every 10 seconds


    def final_df_and_full_text(invoice_path):
        # extracting all tables from the pdf
        all_tables = []
        
        with pdfplumber.open(invoice_path) as pdf:
            for page_no, page in enumerate(pdf.pages, start=1):
                tables = page.extract_tables({
                    "vertical_strategy": "lines",
                    "horizontal_strategy": "lines"
                })
        
                for tbl_id, table in enumerate(tables, start=1):
                    if table is None:
                        continue
        
                    clean_table = [
                        ["" if c is None else c for c in row]
                        for row in table
                    ]
        
                    df = pd.DataFrame(clean_table)
                    df.columns = [f"Col_{i+1}" for i in range(df.shape[1])]
        
                    df["page_no"] = page_no
                    df["table_id"] = tbl_id
        
                    all_tables.append(df)
        
        final_df = pd.concat(all_tables, ignore_index=True)
        
        # extracting all the line from the pdf
        with pdfplumber.open(invoice_path) as pdf:
            full_text = ""
            for page in pdf.pages:
                full_text += page.extract_text() + "\n"
        return final_df, full_text
    
    
        table_data, line_wise_line = final_df_and_full_text(latest_pdf)
        print(table_data)

Latest PDF: C:\Users\yadav\Downloads\JSL Internship codes\JSL Internship Project\Daily Documents\invoice_51109399.pdf
Latest PDF: C:\Users\yadav\Downloads\JSL Internship codes\JSL Internship Project\Daily Documents\invoice_51109399.pdf

KeyboardInterrupt:

In [ ]:
latest_pdf

In [5]:
    def final_df_and_full_text(invoice_path):
        # extracting all tables from the pdf
        all_tables = []
        
        with pdfplumber.open(invoice_path) as pdf:
            for page_no, page in enumerate(pdf.pages, start=1):
                tables = page.extract_tables({
                    "vertical_strategy": "lines",
                    "horizontal_strategy": "lines"
                })
        
                for tbl_id, table in enumerate(tables, start=1):
                    if table is None:
                        continue
        
                    clean_table = [
                        ["" if c is None else c for c in row]
                        for row in table
                    ]
        
                    df = pd.DataFrame(clean_table)
                    df.columns = [f"Col_{i+1}" for i in range(df.shape[1])]
        
                    df["page_no"] = page_no
                    df["table_id"] = tbl_id
        
                    all_tables.append(df)
        
        final_df = pd.concat(all_tables, ignore_index=True)
        
        # extracting all the line from the pdf
        with pdfplumber.open(invoice_path) as pdf:
            full_text = ""
            for page in pdf.pages:
                full_text += page.extract_text() + "\n"
        return final_df, full_text

In [6]:
latest_pdf = r"C:\Users\yadav\Downloads\JSL Internship codes\JSL Internship Project\Process Documents\invoice_51109400.pdf"

In [7]:
table_data, line_wise_line = final_df_and_full_text(latest_pdf)

In [8]:
table_data

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,page_no,table_id
0,No.,Description,Qty,UM,Net Price,Net Worth,VAT %,Gross\nWorth,1,1
1,1.,Boat Rockerz 550 Bluetooth Headphones,1.00,pcs,"3,397.00","3,397.00",10%,"3,736.70",1,1
2,2.,Samsung Galaxy Buds2 Pro Graphite,9.00,pcs,"14,758.00","132,822.00",10%,"146,104.20",1,1
3,,VAT %,Net Worth,VAT,Gross Worth,NaN,NaN,NaN,1,2
4,,10%,"136,219.00","13,621.90","149,840.90",NaN,NaN,NaN,1,2
5,Total,,"INR 136,219.00","INR 13,621.90","INR 149,840.90",NaN,NaN,NaN,1,2

In [9]:
table_data[['Col_1', 'Col_2', 'Col_3', 'Col_4', 'Col_5', 'Col_6', 'Col_7', 'Col_8']]

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8
0,No.,Description,Qty,UM,Net Price,Net Worth,VAT %,Gross\nWorth
1,1.,Boat Rockerz 550 Bluetooth Headphones,1.00,pcs,"3,397.00","3,397.00",10%,"3,736.70"
2,2.,Samsung Galaxy Buds2 Pro Graphite,9.00,pcs,"14,758.00","132,822.00",10%,"146,104.20"
3,,VAT %,Net Worth,VAT,Gross Worth,NaN,NaN,NaN
4,,10%,"136,219.00","13,621.90","149,840.90",NaN,NaN,NaN
5,Total,,"INR 136,219.00","INR 13,621.90","INR 149,840.90",NaN,NaN,NaN

In [10]:
invoice_number_line = line_wise_line.split("\n")[0]
invoice_number = invoice_number_line.split(":")[1]
print("invoice number :",invoice_number)

invoice number :  51109400

In [11]:
date_of_issue_line = line_wise_line.split("\n")[1]
date_of_issue = date_of_issue_line.split(":")[1]
print("date of issue :", date_of_issue)

date of issue :  22/02/2024

In [35]:
table_data

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,page_no,table_id
0,No.,Description,Qty,UM,Net Price,Net Worth,VAT %,Gross\nWorth,1,1
1,1.,Boat Rockerz 550 Bluetooth Headphones,1.00,pcs,"3,397.00","3,397.00",10%,"3,736.70",1,1
2,2.,Samsung Galaxy Buds2 Pro Graphite,9.00,pcs,"14,758.00","132,822.00",10%,"146,104.20",1,1
3,,VAT %,Net Worth,VAT,Gross Worth,NaN,NaN,NaN,1,2
4,,10%,"136,219.00","13,621.90","149,840.90",NaN,NaN,NaN,1,2
5,Total,,"INR 136,219.00","INR 13,621.90","INR 149,840.90",NaN,NaN,NaN,1,2

In [12]:
# ["No.", "Description", "Qty", "UM", "Net Price", "Net Worth", "VAT %", "Gross Worth"] 

columns_li = []

for a in table_data.columns: 
    for b in range(2): 
        if "No." in str(table_data[a][b]):
            columns_li.append(a) 
        elif "Description" in str(table_data[a][b]): 
            columns_li.append(a)
        elif "Qty" in str(table_data[a][b]): 
            columns_li.append(a)
        elif "UM" in str(table_data[a][b]):
            columns_li.append(a)
        elif "Net Price" in str(table_data[a][b]):
            columns_li.append(a)
        elif "Net Worth" in str(table_data[a][b]):
            columns_li.append(a)
        elif "VAT %" in str(table_data[a][b]): 
            columns_li.append(a)
        elif "Gross" in str(table_data[a][b]): 
            columns_li.append(a)

In [33]:
table_data["Col_1"][2]

'2.'

In [30]:
table_data[columns_li].iloc[:3,:]

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8
0,No.,Description,Qty,UM,Net Price,Net Worth,VAT %,Gross\nWorth
1,1.,Boat Rockerz 550 Bluetooth Headphones,1.00,pcs,"3,397.00","3,397.00",10%,"3,736.70"
2,2.,Samsung Galaxy Buds2 Pro Graphite,9.00,pcs,"14,758.00","132,822.00",10%,"146,104.20"

In [37]:
table_data[columns_li].iloc[3:,:]

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8
3,,VAT %,Net Worth,VAT,Gross Worth,NaN,NaN,NaN
4,,10%,"136,219.00","13,621.90","149,840.90",NaN,NaN,NaN
5,Total,,"INR 136,219.00","INR 13,621.90","INR 149,840.90",NaN,NaN,NaN

In [13]:
columns_li.append('data_')

In [19]:
table_data["Col_1"][1]

'1.'

In [21]:
for b in range(2): 
        if "No." in str(table_data[a][b]):
            columns_li.append(a)