In [50]:
!pip install pdfplumber

Requirement already satisfied: pdfplumber in c:\users\pritam.moharana\appdata\local\anaconda3\lib\site-packages (0.11.7)
Requirement already satisfied: pdfminer.six==20250506 in c:\users\pritam.moharana\appdata\local\anaconda3\lib\site-packages (from pdfplumber) (20250506)
Requirement already satisfied: Pillow>=9.1 in c:\users\pritam.moharana\appdata\local\anaconda3\lib\site-packages (from pdfplumber) (11.1.0)
Requirement already satisfied: pypdfium2>=4.18.0 in c:\users\pritam.moharana\appdata\local\anaconda3\lib\site-packages (from pdfplumber) (4.30.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\pritam.moharana\appdata\local\anaconda3\lib\site-packages (from pdfminer.six==20250506->pdfplumber) (3.3.2)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\pritam.moharana\appdata\local\anaconda3\lib\site-packages (from pdfminer.six==20250506->pdfplumber) (44.0.1)
Requirement already satisfied: cffi>=1.12 in c:\users\pritam.moharana\appdata\local\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in c:\users\pritam.moharana\appdata\local\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (2.21)

In [2]:
import pdfplumber
import pandas as pd

In [3]:
invoice_path = r"C:\Users\pritam.moharana\OneDrive - jindalstainless.com\Desktop\Study Material\Personal\Invoices pdfs\Daily Documents\invoice_51109301.pdf"

In [4]:
def final_df_and_full_text(invoice_path):
    # extracting all tables from the pdf
    all_tables = []
    
    with pdfplumber.open(invoice_path) as pdf:
        for page_no, page in enumerate(pdf.pages, start=1):
            tables = page.extract_tables({
                "vertical_strategy": "lines",
                "horizontal_strategy": "lines"
            })
    
            for tbl_id, table in enumerate(tables, start=1):
                if table is None:
                    continue
    
                clean_table = [
                    ["" if c is None else c for c in row]
                    for row in table
                ]
    
                df = pd.DataFrame(clean_table)
                df.columns = [f"Col_{i+1}" for i in range(df.shape[1])]
    
                df["page_no"] = page_no
                df["table_id"] = tbl_id
    
                all_tables.append(df)
    
    final_df = pd.concat(all_tables, ignore_index=True)
    
    # extracting all the line from the pdf
    with pdfplumber.open(invoice_path) as pdf:
        full_text = ""
        for page in pdf.pages:
            full_text += page.extract_text() + "\n"
    return final_df, full_text

In [6]:
final_df, full_text = final_df_and_full_text(invoice_path)

In [1]:
final_df.columns

NameError: name 'final_df' is not defined

In [52]:
full_text.split("\n")

['Invoice no: 51109301',
 'Date of issue: 03/07/2023',
 'Seller: Client:',
 'TechVision Distributors Pvt Ltd Raj Electronics Pvt Ltd',
 'Plot 14, MIDC Industrial Area, Andheri East 42 MG Road',
 'Mumbai, Maharashtra - 400093 Bengaluru, Karnataka - 560001',
 'Tax Id: 27AABCT1234F1Z5 Tax Id: 901-95-4704',
 'GSTIN: 27AABCT1234F1Z5',
 'ITEMS',
 'No. Description Qty UM Net Price Net Worth VAT % Gross',
 'Worth',
 '1. Garmin Fenix 7 Solar Multisport GPS 9.00 pcs 74,120.00 667,080.00 10% 733,788.00',
 '2. Apple Watch Series 9 GPS 45mm 8.00 pcs 52,083.00 416,664.00 10% 458,330.40',
 'Midnight',
 '3. Xiaomi 14 Pro 512GB White 8.00 pcs 74,154.00 593,232.00 10% 652,555.20',
 'SUMMARY',
 'VAT % Net Worth VAT Gross Worth',
 '10% 1,676,976.00 167,697.60 1,844,673.60',
 'INR',
 'Total INR 1,676,976.00 INR 1,844,673.60',
 '167,697.60',
 '']

In [57]:
# Invoice No 
invoice_number_line = full_text.split("\n")[0]
invoice_number = invoice_number_line.split(":")[1]
print("Invoice Number : ",invoice_number)

Invoice Number :   51109301

In [58]:
# Date of issue
date_of_issue_line = full_text.split("\n")[1]
date_of_issue = date_of_issue_line.split(":")[1]
print("Date of Issue : ",date_of_issue)

Date of Issue :   03/07/2023

In [17]:
final_df

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,page_no,table_id
0,No.,Description,Qty,UM,Net Price,Net Worth,VAT %,Gross\nWorth,1,1
1,1.,Garmin Fenix 7 Solar Multisport GPS,9.00,pcs,"74,120.00","667,080.00",10%,"733,788.00",1,1
2,2.,Apple Watch Series 9 GPS 45mm\nMidnight,8.00,pcs,"52,083.00","416,664.00",10%,"458,330.40",1,1
3,3.,Xiaomi 14 Pro 512GB White,8.00,pcs,"74,154.00","593,232.00",10%,"652,555.20",1,1
4,,VAT %,Net Worth,VAT,Gross Worth,NaN,NaN,NaN,1,2
5,,10%,"1,676,976.00","167,697.60","1,844,673.60",NaN,NaN,NaN,1,2
6,Total,,"INR 1,676,976.00","INR\n167,697.60","INR 1,844,673.60",NaN,NaN,NaN,1,2

In [31]:
# ["No.", "Description", "Qty", "UM", "Net Price", "Net Worth", "VAT %", "Gross Worth"] 

columns_li = []

for a in final_df.columns: 
    for b in range(2): 
        if "No." in str(final_df[a][b]):
            columns_li.append(a) 
        elif "Description" in str(final_df[a][b]): 
            columns_li.append(a)
        elif "Qty" in str(final_df[a][b]): 
            columns_li.append(a)
        elif "UM" in str(final_df[a][b]):
            columns_li.append(a)
        elif "Net Price" in str(final_df[a][b]):
            columns_li.append(a)
        elif "Net Worth" in str(final_df[a][b]):
            columns_li.append(a)
        elif "VAT %" in str(final_df[a][b]): 
            columns_li.append(a)
        elif "Gross" in str(final_df[a][b]): 
            columns_li.append(a)

In [35]:
uncleaned_df_for_first_table = final_df[columns_li]
uncleaned_df_for_first_table

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8
0,No.,Description,Qty,UM,Net Price,Net Worth,VAT %,Gross\nWorth
1,1.,Garmin Fenix 7 Solar Multisport GPS,9.00,pcs,"74,120.00","667,080.00",10%,"733,788.00"
2,2.,Apple Watch Series 9 GPS 45mm\nMidnight,8.00,pcs,"52,083.00","416,664.00",10%,"458,330.40"
3,3.,Xiaomi 14 Pro 512GB White,8.00,pcs,"74,154.00","593,232.00",10%,"652,555.20"
4,,VAT %,Net Worth,VAT,Gross Worth,NaN,NaN,NaN
5,,10%,"1,676,976.00","167,697.60","1,844,673.60",NaN,NaN,NaN
6,Total,,"INR 1,676,976.00","INR\n167,697.60","INR 1,844,673.60",NaN,NaN,NaN

In [39]:
for d in range(len(uncleaned_df_for_first_table)): 
    if "VAT %" in str(uncleaned_df_for_first_table["Col_2"][d]):
        row_index = d

In [40]:
row_index

4

In [43]:
cleaned_df_of_items = uncleaned_df_for_first_table.iloc[:row_index,:]
cleaned_df_of_items

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8
0,No.,Description,Qty,UM,Net Price,Net Worth,VAT %,Gross\nWorth
1,1.,Garmin Fenix 7 Solar Multisport GPS,9.00,pcs,"74,120.00","667,080.00",10%,"733,788.00"
2,2.,Apple Watch Series 9 GPS 45mm\nMidnight,8.00,pcs,"52,083.00","416,664.00",10%,"458,330.40"
3,3.,Xiaomi 14 Pro 512GB White,8.00,pcs,"74,154.00","593,232.00",10%,"652,555.20"